/**:
  ros__parameters:
    # 토픽 송수신을 위해서 선언한 파라미터
    topic_offboard_control_mode: "/fmu/in/offboard_control_mode"
    topic_vehicle_attitude_setpoint: "/fmu/in/vehicle_attitude_setpoint"
    topic_trajectory_setpoint: "/fmu/in/trajectory_setpoint"
    topic_vehicle_command: "/fmu/in/vehicle_command"
    topic_vehicle_local_position: "/fmu/out/vehicle_local_position"
    topic_vehicle_attitude: "/fmu/out/vehicle_attitude"
    topic_vehicle_status: "/fmu/out/vehicle_status"
    topic_vehicle_global_position: "/fmu/out/vehicle_global_position"
    
    # 거리에 도착했는지 아닌지를 판독하기 위해서 필요한 값
    threshold_range: 2.0
